"""initial schema

Revision ID: 28c7ae36c892
Revises: 
Create Date: 2026-09-27 17:49:22.264350
"""
from alembic import op
import sqlalchemy as sa


revision = '28c7ae36c892'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_repo_id'), 'jobs', ['repo_id'], unique=False)
    op.create_table('llm_cache',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('repos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=False),
    sa.Column('last_ingested_commit', sa.String(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('stats_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('emails_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_repo_id'), 'authors', ['repo_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('alternatives', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('skill_hash', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_repo_id'), 'decisions', ['repo_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('loc', sa.Integer(), nullable=False),
    sa.Column('is_entry_point', sa.Boolean(), nullable=False),
    sa.Column('fan_in', sa.Integer(), nullable=False),
    sa.Column('fan_out', sa.Integer(), nullable=False),
    sa.Column('bus_factor', sa.Integer(), nullable=True),
    sa.Column('at_risk', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'path', name='uq_files_repo_path')
    )
    op.create_index(op.f('ix_files_path'), 'files', ['path'], unique=False)
    op.create_index(op.f('ix_files_repo_id'), 'files', ['repo_id'], unique=False)
    op.create_table('commits',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_commits_author_id'), 'commits', ['author_id'], unique=False)
    op.create_index(op.f('ix_commits_repo_id'), 'commits', ['repo_id'], unique=False)
    op.create_table('coupling',
    sa.Column('file_a_id', sa.Integer(), nullable=False),
    sa.Column('file_b_id', sa.Integer(), nullable=False),
    sa.Column('co_changes', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['file_a_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['file_b_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('file_a_id', 'file_b_id')
    )
    op.create_index('ix_coupling_a', 'coupling', ['file_a_id'], unique=False)
    op.create_index('ix_coupling_b', 'coupling', ['file_b_id'], unique=False)
    op.create_table('decision_files',
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('decision_id', 'file_id')
    )
    op.create_index('ix_decision_files_decision', 'decision_files', ['decision_id'], unique=False)
    op.create_index('ix_decision_files_file', 'decision_files', ['file_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'type', 'ref', name='uq_evidence_repo_type_ref')
    )
    op.create_index(op.f('ix_evidence_author_id'), 'evidence', ['author_id'], unique=False)
    op.create_index(op.f('ix_evidence_repo_id'), 'evidence', ['repo_id'], unique=False)
    op.create_table('imports',
    sa.Column('src_file_id', sa.Integer(), nullable=False),
    sa.Column('dst_file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dst_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['src_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('src_file_id', 'dst_file_id')
    )
    op.create_index('ix_imports_dst', 'imports', ['dst_file_id'], unique=False)
    op.create_index('ix_imports_src', 'imports', ['src_file_id'], unique=False)
    op.create_table('ownership',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('blame_share', sa.Float(), nullable=False),
    sa.Column('recent_share', sa.Float(), nullable=False),
    sa.Column('ownership', sa.Float(), nullable=False),
    sa.Column('last_commit_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('file_id', 'author_id')
    )
    op.create_index('ix_ownership_author', 'ownership', ['author_id'], unique=False)
    op.create_index('ix_ownership_file', 'ownership', ['file_id'], unique=False)
    op.create_table('commit_files',
    sa.Column('commit_hash', sa.String(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('added', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commit_hash'], ['commits.hash'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('commit_hash', 'file_id')
    )
    op.create_index('ix_commit_files_commit', 'commit_files', ['commit_hash'], unique=False)
    op.create_index('ix_commit_files_file', 'commit_files', ['file_id'], unique=False)
    op.create_table('decision_evidence',
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('decision_id', 'evidence_id')
    )
    op.create_index('ix_decision_evidence_decision', 'decision_evidence', ['decision_id'], unique=False)
    op.create_index('ix_decision_evidence_evidence', 'decision_evidence', ['evidence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_decision_evidence_evidence', table_name='decision_evidence')
    op.drop_index('ix_decision_evidence_decision', table_name='decision_evidence')
    op.drop_table('decision_evidence')
    op.drop_index('ix_commit_files_file', table_name='commit_files')
    op.drop_index('ix_commit_files_commit', table_name='commit_files')
    op.drop_table('commit_files')
    op.drop_index('ix_ownership_file', table_name='ownership')
    op.drop_index('ix_ownership_author', table_name='ownership')
    op.drop_table('ownership')
    op.drop_index('ix_imports_src', table_name='imports')
    op.drop_index('ix_imports_dst', table_name='imports')
    op.drop_table('imports')
    op.drop_index(op.f('ix_evidence_repo_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_author_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_decision_files_file', table_name='decision_files')
    op.drop_index('ix_decision_files_decision', table_name='decision_files')
    op.drop_table('decision_files')
    op.drop_index('ix_coupling_b', table_name='coupling')
    op.drop_index('ix_coupling_a', table_name='coupling')
    op.drop_table('coupling')
    op.drop_index(op.f('ix_commits_repo_id'), table_name='commits')
    op.drop_index(op.f('ix_commits_author_id'), table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_files_repo_id'), table_name='files')
    op.drop_index(op.f('ix_files_path'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_decisions_repo_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_authors_repo_id'), table_name='authors')
    op.drop_table('authors')
    op.drop_table('repos')
    op.drop_table('llm_cache')
    op.drop_index(op.f('ix_jobs_repo_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
